<?xml version="1.0" encoding="UTF-8"?>
<Profile xmlns="http://soap.sforce.com/2006/04/metadata">
    <applicationVisibilities>
        <application>%%%NAMESPACE%%%NPPatch_Lightning</application>
        <default>true</default>
        <visible>true</visible>
    </applicationVisibilities>
    <layoutAssignments>
        <layout>Account-Household Layout</layout>
        <recordType>Account.%%%NAMESPACE%%%HH_Account</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Account-Organization Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Account-Organization Layout</layout>
        <recordType>Account.%%%NAMESPACE%%%Organization</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Campaign-NPPatch Campaign Layout</layout>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Opportunity-Donation Layout</layout>
        <recordType>Opportunity.NPPatch_Default</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Opportunity-Donation Layout</layout>
        <recordType>Opportunity.%%%NAMESPACE%%%Donation</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Opportunity-Grant Layout</layout>
        <recordType>Opportunity.%%%NAMESPACE%%%Grant</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Opportunity-In-Kind Gift Layout</layout>
        <recordType>Opportunity.%%%NAMESPACE%%%InKindGift</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Opportunity-Major Gift Layout</layout>
        <recordType>Opportunity.%%%NAMESPACE%%%MajorGift</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Opportunity-Matching Gift Layout</layout>
        <recordType>Opportunity.%%%NAMESPACE%%%MatchingGift</recordType>
    </layoutAssignments>
    <layoutAssignments>
        <layout>Opportunity-Membership Layout</layout>
        <recordType>Opportunity.%%%NAMESPACE%%%Membership</recordType>
    </layoutAssignments>
    <recordTypeVisibilities>
        <default>true</default>
        <recordType>Opportunity.%%%NAMESPACE%%%Donation</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Opportunity.%%%NAMESPACE%%%Grant</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Opportunity.%%%NAMESPACE%%%InKindGift</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Opportunity.%%%NAMESPACE%%%MajorGift</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Opportunity.%%%NAMESPACE%%%MatchingGift</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Opportunity.%%%NAMESPACE%%%Membership</recordType>
        <visible>true</visible>
    </recordTypeVisibilities>
    <recordTypeVisibilities>
        <default>false</default>
        <recordType>Opportunity.NPPatch_Default</recordType>
        <visible>false</visible>
    </recordTypeVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%Address__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%Batch_Gift_Entry</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%Contact_Merge</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%DataImport__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%DataImportBatch__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%Engagement_Plan_Template__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%General_Accounting_Unit__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%Level__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%NPPatch_Resources</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%NPPatch_Settings</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%OppPayment__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%Relationship__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%Affiliation__c</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
    <tabVisibilities>
        <tab>%%%NAMESPACE%%%GE_Gift_Entry</tab>
        <visibility>DefaultOn</visibility>
    </tabVisibilities>
</Profile>
